site_name: Rimses Docs

nav:
  # - Home: index.md
  # - Rimses:
  - Single:
    - Step 1 Create the Rimses database: step1.md
    - Step 2 Install the Rimses program on a workstation or terminal server: step2.md
    - Step 3 Set referential integrity on the Rimses database structure : step3.md
  - Final steps:
    - Step 4 Install add-ons? : step4.md
    - Step 5 Verify installation: step5.md
  - Testing: testing.md
  # - Multi:
  #   -Testing structure: step1.md

formats:
  - pdf

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

theme: readthedocs
# theme:
#   name: material
extra_css: 
  - stylesheet/extra.css