site_name: testing name

nav:
  # - Home: index.md
  - Step 1 Create the Rimses database: step1.md
  - Step 2 Install the Rimses program on a workstation or terminal server: step2.md
  - Step 3 Set referential integrity on the Rimses database structure : step3.md
  - Final steps:
    - Step 4 Install add-ons? : step4.md
    - Step 5 Verify installation: step5.md
  - Testing: testing.md
  
theme: readthedocs
extra_css: 
  - stylesheet/extra.css